name: Synchronize DB
on:
  workflow_dispatch:
permissions:
  actions: read
jobs:
  synchronize-db:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Ivy 🛎
        uses: actions/checkout@v3
        with:
          path: ivy
          persist-credentials: false
          submodules: "recursive"
          fetch-depth: 1

      - name: Synchronize DB
        run: |
          pip install pymongo
          cd ivy
          python run_tests_CLI/synchronize_db.py ${{ secrets.MONGODB_PASSWORD }}